AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM Template for your FastAPI application

Globals:
  Function:
    Timeout: 720

Resources:
  FastAPILambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: FastAPILambdaFunction
      ImageUri: sports-model-lambda
      MemorySize: 3008
      Environment:
        Variables:
          LOCALHOST: "False"
          ENVIRONMENT: "PROD"
          ADMIN_API_KEY: "s8y8dfcqcfXarutIS6EqCreVzaBsDI9S"
          FRONT_END_API_KEY: "KAYBxlOSgwIbxaoGxfqG0n1IHW0vbLRX"
          READ_API_KEY: "gYa5FgUYw2CdcxpKqoTo0VgZRisiooQV"
          NBA_API_KEY: "gO1bWOaTuq8mdmoLPNut9TmM9qjEzmA0"
          AWS_API_KEY: "ApeJmM3hS9k53Ya2zqMPcXuMFsn1Ksny"

      Events:
        FastAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
