AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM Template for your FastAPI application

Parameters:
  Localhost:
    Type: String
    Default: "False"
  EnvironmentName:
    Type: String
    Default: "PROD"
  AdminApiKey:
    Type: String
    NoEcho: true
  FrontEndApiKey:
    Type: String
    NoEcho: true
  ReadApiKey:
    Type: String
    NoEcho: true
  NbaApiKey:
    Type: String
    NoEcho: true
  AwsApiKey:
    Type: String
    NoEcho: true
  SupabaseDbUrl:
    Type: String
    NoEcho: true
  SupabaseSchema:
    Type: String
    Default: sports_models

Globals:
  Function:
    Timeout: 720

Resources:
  FastAPILambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: FastAPILambdaFunction
      ImageUri: sports-model-lambda
      MemorySize: 8000
      Environment:
        Variables:
          LOCALHOST: !Ref Localhost
          ENVIRONMENT: !Ref EnvironmentName
          ADMIN_API_KEY: !Ref AdminApiKey
          FRONT_END_API_KEY: !Ref FrontEndApiKey
          READ_API_KEY: !Ref ReadApiKey
          NBA_API_KEY: !Ref NbaApiKey
          AWS_API_KEY: !Ref AwsApiKey
          SUPABASE_DB_URL: !Ref SupabaseDbUrl
          SUPABASE_SCHEMA: !Ref SupabaseSchema

      Events:
        FastAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
